name: Tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GH
        uses: actions/checkout@v3.2.0

      - name: Set up python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: "3.10"

      - name: Install python packages
        run: make

      - name: Check formating and typing
        run: make lint
